apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tcpdump.fullname" . }}
  labels:
    {{- include "tcpdump.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
